### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Itamar1337** [viktorashi/bingobaker.com-autoplayer#2]
why not use requests to generate the cards & websockets to mark them? would speed it up by a ton

**Comment by viktorashi** [comment]
> why not use requests to generate the cards & websockets to mark them? would speed it up by a ton

Regarding the second one, marking them I've just realised (in the latest release) I can just save the entire data for the card in the cards.txt instead of just the links and I can do the check in memory in literally a quarter of a second instead of waiting for the browser to play itself whole it's even glitchy and stuff

For the first one, yep that'd be a good optimization if I knew how to do it, the web traffic might need to be analized to see what happens when I request a new card, but for now the thing that took most of the time and was the glitchiest is fixed, you can message me on discord 
vik2801 to give you a bit of a demo if you wanna, also how come you found this repo?=))

**Comment by viktorashi** [comment]
> > why not use requests to generate the cards & websockets to mark them? would speed it up by a ton
> 
> Regarding the second one, marking them I've just realised (in the latest release) I can just save the entire data for the card in the cards.txt instead of just the links and I can do the check in memory in literally a quarter of a second instead of waiting for the browser to play itself whole it's even glitchy and stuff
> 
> For the first one, yep that'd be a good optimization if I knew how to do it, the web traffic might need to be analized to see what happens when I request a new card, but for now the thing that took most of the time and was the glitchiest is fixed, you can message me on discord 
> vik2801 to give you a bit of a demo if you wanna, also how come you found this repo?=))

Btw don't use the current version, it's buggy, use the latest release pls
